# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
kotlin.code.style=official
android.useAndroidX=true
android.uniquePackageNames=false
android.r8.strictFullModeForKeepRules=false

# Opt-out of AGP 9.0 built-in Kotlin support to resolve conflict with kotlin-android plugin
android.builtInKotlin=false
android.newDsl=false
