# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
kotlin.code.style=official
android.useAndroidX=true
android.uniquePackageNames=false
android.r8.strictFullModeForKeepRules=false

# ?????????? KSP ?? ????? ???????? ???????? ??? ? Kotlin SourceSets
android.disallowKotlinSourceSets=false
